/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./*.html"],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                outline: "#77767b",
                "secondary-container": "#e2165f",
                "on-primary-fixed": "#1b1b1e",
                "on-secondary": "#ffffff",
                "on-tertiary-fixed-variant": "#494640",
                "primary-container": "#1b1b1e",
                "error-container": "#ffdad6",
                "primary-fixed-dim": "#c8c5ca",
                "surface-container": "#f1eded",
                "surface-stone": "#f8f8f7",
                primary: "#8B263E",
                "inverse-primary": "#c8c5ca",
                "on-secondary-container": "#fffbff",
                "on-error": "#ffffff",
                "kds-yellow": "#C5A059",
                "on-primary-container": "#858387",
                "tertiary-container": "#1d1b16",
                "outline-variant": "#E2DFD8",
                background: "#ffffff",
                "surface-container-highest": "#e5e2e1",
                secondary: "#000000",
                "on-tertiary-fixed": "#1d1b16",
                "kds-blue": "#2E4057",
                "on-secondary-fixed-variant": "#900038",
                "inverse-on-surface": "#f4f0ef",
                "kds-pink": "#8B263E",
                "surface-bright": "#ffffff",
                error: "#ba1a1a",
                "on-primary-fixed-variant": "#47464a",
                "secondary-fixed": "#ffd9de",
                "kds-purple": "#836096",
                "on-error-container": "#93000a",
                "secondary-fixed-dim": "#ffb2be",
                "tertiary-fixed": "#e8e2d9",
                tertiary: "#000000",
                "on-background": "#1c1b1c",
                "surface-container-low": "#f7f3f2",
                "inverse-surface": "#313030",
                "on-tertiary-container": "#88837c",
                "on-primary": "#000000",
                "surface-dim": "#ddd9d9",
                "surface-variant": "#e5e2e1",
                "on-secondary-fixed": "#400014",
                "zinc-900": "#111111",
                "surface-container-high": "#ebe7e7",
                "on-surface": "#1c1b1c",
                "zinc-600": "#555555",
                "surface-tint": "#5f5e61",
                "primary-fixed": "#e4e1e6",
                "tertiary-fixed-dim": "#cbc6bd",
                "on-surface-variant": "#47464b",
                "surface-container-lowest": "#ffffff",
                "kds-orange": "#D05A3F",
                surface: "#ffffff",
                "on-tertiary": "#ffffff",
                "sanat-yellow": "#8B263E",
                "sanat-yellow-dark": "#6d1e30",
                "sanat-dark": "#000000",
                "sanat-blue": "#58acf5",
                "sanat-blue-dark": "#4b93d0"
            },
            borderRadius: {
                none: "0px",
                sm: "0.75rem",
                DEFAULT: "0.75rem",
                md: "0.75rem",
                lg: "0.75rem",
                xl: "0.75rem",
                "2xl": "0.75rem",
                "3xl": "0.75rem",
                full: "9999px"
            },
            spacing: {
                "margin-desktop": "80px",
                "section-gap": "120px",
                "container-max": "1200px",
                gutter: "24px",
                "margin-mobile": "20px"
            },
            fontFamily: {
                "headline-lg": ["SF Pro Display", "sans-serif"],
                "label-md": ["SF Pro Display", "sans-serif"],
                "headline-lg-mobile": ["SF Pro Display", "sans-serif"],
                "headline-md": ["SF Pro Display", "sans-serif"],
                "display-lg": ["SF Pro Display", "sans-serif"],
                "body-md": ["SF Pro Display", "sans-serif"],
                "body-lg": ["SF Pro Display", "sans-serif"]
            },
            fontSize: {
                "headline-lg": ["30px", { lineHeight: "38px", fontWeight: "700" }],
                "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
                "headline-lg-mobile": ["24px", { lineHeight: "30px", fontWeight: "700" }],
                "headline-md": ["20px", { lineHeight: "26px", fontWeight: "600" }],
                "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "700" }],
                "body-md": ["15px", { lineHeight: "22px", fontWeight: "400" }],
                "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }]
            }
        }
    },
    plugins: [
        require("@tailwindcss/forms"),
        require("@tailwindcss/container-queries")
    ]
};
