/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./*.html"],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                                outline: "#77767b",
                "secondary-container": "#e2165f",
                "on-primary-fixed": "#1b1b1e",
                "on-secondary": "#ffffff",
                "on-tertiary-fixed-variant": "#494640",
                "primary-container": "#1b1b1e",
                "error-container": "#ffdad6",
                "primary-fixed-dim": "#c8c5ca",
                "surface-container": "#f1eded",
                "surface-stone": "#f8f8f7",
                primary: "#000000",
                "inverse-primary": "#c8c5ca",
                "on-secondary-container": "#fffbff",
                "on-error": "#ffffff",
                                "kds-yellow": "#C5A059",
                "on-primary-container": "#858387",
                "tertiary-container": "#1d1b16",
                "outline-variant": "#E2DFD8",
                background: "#FDFBF7",
                "surface-container-highest": "#e5e2e1",
                secondary: "#B03B4D",
                "on-tertiary-fixed": "#1d1b16",
                "kds-blue": "#2E4057",
                "on-secondary-fixed-variant": "#900038",
                "inverse-on-surface": "#f4f0ef",
                "kds-pink": "#8B263E",
                "surface-bright": "#FDFBF7",
                error: "#ba1a1a",
                "on-primary-fixed-variant": "#47464a",
                "secondary-fixed": "#ffd9de",
                "kds-purple": "#5D3754",
                "on-error-container": "#93000a",
                "secondary-fixed-dim": "#ffb2be",
                "tertiary-fixed": "#e8e2d9",
                tertiary: "#000000",
                "on-background": "#1c1b1c",
                "surface-container-low": "#f7f3f2",
                "inverse-surface": "#313030",
                "on-tertiary-container": "#88837c",
                "on-primary": "#ffffff",
                "surface-dim": "#ddd9d9",
                "surface-variant": "#e5e2e1",
                "on-secondary-fixed": "#400014",
                "zinc-900": "#1E1E22",
                "surface-container-high": "#ebe7e7",
                "on-surface": "#1c1b1c",
                "zinc-600": "#5A5A62",
                "surface-tint": "#5f5e61",
                "primary-fixed": "#e4e1e6",
                "tertiary-fixed-dim": "#cbc6bd",
                "on-surface-variant": "#47464b",
                "surface-container-lowest": "#ffffff",
                "kds-orange": "#D05A3F",
                surface: "#F8F6F0",
                "on-tertiary": "#ffffff"
            },
            borderRadius: {
                none: "0px",
                sm: "0.75rem",
                DEFAULT: "0.75rem",
                md: "0.75rem",
                lg: "0.75rem",
                xl: "0.75rem",
                "2xl": "0.75rem",
                "3xl": "0.75rem",
                full: "0.75rem"
            },
            spacing: {
                "margin-desktop": "80px",
                "section-gap": "120px",
                "container-max": "1280px",
                gutter: "24px",
                "margin-mobile": "20px"
            },
            fontFamily: {
                "headline-lg": ["SF Pro Display", "sans-serif"],
                "label-md": ["SF Pro Display", "sans-serif"],
                "headline-lg-mobile": ["SF Pro Display", "sans-serif"],
                "headline-md": ["SF Pro Display", "sans-serif"],
                "display-lg": ["SF Pro Display", "sans-serif"],
                "body-md": ["SF Pro Display", "sans-serif"],
                "body-lg": ["SF Pro Display", "sans-serif"]
            },
            fontSize: {
                "headline-lg": ["30px", { lineHeight: "38px", fontWeight: "700" }],
                "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.05em", fontWeight: "600" }],
                "headline-lg-mobile": ["25px", { lineHeight: "32px", fontWeight: "700" }],
                "headline-md": ["21px", { lineHeight: "28px", fontWeight: "600" }],
                "display-lg": ["42px", { lineHeight: "50px", letterSpacing: "-0.02em", fontWeight: "700" }],
                "body-md": ["15px", { lineHeight: "23px", fontWeight: "400" }],
                "body-lg": ["16px", { lineHeight: "25px", fontWeight: "400" }]
            }
        }
    },
    plugins: [
        require("@tailwindcss/forms"),
        require("@tailwindcss/container-queries")
    ]
};
